[theme]
base = "light"
primaryColor = "#aa5d83"
backgroundColor = "#f5ead8"
secondaryBackgroundColor = "#ebddc5"
textColor = "#201e1d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 5
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
